# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 18:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20180208_1242'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAssessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_title', models.CharField(max_length=100)),
                ('assessment_type', models.CharField(max_length=50)),
                ('assessment_weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('assessment_duration', models.PositiveSmallIntegerField()),
                ('assessment_hand_out', models.CharField(choices=[('1A', 'Autumn Week 1'), ('2A', 'Autumn Week 2'), ('3A', 'Autumn Week 3'), ('4A', 'Autumn Week 4'), ('5A', 'Autumn Week 5'), ('6A', 'Autumn Week 6'), ('7A', 'Autumn Week 7'), ('8A', 'Autumn Week 8'), ('9A', 'Autumn Week 9'), ('10A', 'Autumn Week 10'), ('11A', 'Autumn Week 11'), ('1S', 'Spring Week 1'), ('2S', 'Spring Week 2'), ('3S', 'Spring Week 3'), ('4S', 'Spring Week 4'), ('5S', 'Spring Week 5'), ('6S', 'Spring Week 6'), ('7S', 'Spring Week 7'), ('8S', 'Spring Week 8'), ('9S', 'Spring Week 9'), ('10S', 'Spring Week 10'), ('11S', 'Spring Week 11')], max_length=15)),
                ('assessment_hand_in', models.CharField(choices=[('1A', 'Autumn Week 1'), ('2A', 'Autumn Week 2'), ('3A', 'Autumn Week 3'), ('4A', 'Autumn Week 4'), ('5A', 'Autumn Week 5'), ('6A', 'Autumn Week 6'), ('7A', 'Autumn Week 7'), ('8A', 'Autumn Week 8'), ('9A', 'Autumn Week 9'), ('10A', 'Autumn Week 10'), ('11A', 'Autumn Week 11'), ('1S', 'Spring Week 1'), ('2S', 'Spring Week 2'), ('3S', 'Spring Week 3'), ('4S', 'Spring Week 4'), ('5S', 'Spring Week 5'), ('6S', 'Spring Week 6'), ('7S', 'Spring Week 7'), ('8S', 'Spring Week 8'), ('9S', 'Spring Week 9'), ('10S', 'Spring Week 10'), ('11S', 'Spring Week 11')], max_length=15)),
                ('assessment_semester', models.CharField(choices=[('Autumn Semester', 'Autumn Semester'), ('Spring Semester', 'Spring Semester')], max_length=15)),
                ('learning_outcomes_covered', models.CharField(max_length=500)),
                ('module_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Module')),
            ],
        ),
    ]
