# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20180215_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleteaching',
            name='teaching_practical_workshops',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Practical classes and workshops'),
        ),
    ]
