# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20180216_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldEntity',
            fields=[
                ('entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_title', models.CharField(max_length=50, verbose_name='Title/Label')),
                ('entity_type', models.CharField(choices=[('text-input', 'Text Input'), ('text-area', 'Text Area'), ('multi-choice', 'Select Box'), ('check-boxes', 'Check Boxes')], max_length=12, verbose_name='Type')),
                ('entity_description', models.CharField(blank=True, max_length=1000, verbose_name='Description')),
                ('entity_placeholder', models.CharField(blank=True, max_length=100, verbose_name='Placeholder')),
                ('entity_max_length', models.PositiveSmallIntegerField(default=100, verbose_name='Max Length')),
            ],
        ),
    ]
