# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_formfieldentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleassessment',
            name='assessment_semester',
            field=models.CharField(blank=True, choices=[('Autumn Semester', 'Autumn Semester'), ('Spring Semester', 'Spring Semester')], max_length=15, verbose_name='Semester'),
        ),
    ]
