# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20180222_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfieldentity',
            old_name='entity_title',
            new_name='entity_label',
        ),
        migrations.AddField(
            model_name='formfieldentity',
            name='entity_default',
            field=models.CharField(blank=True, max_length=100, verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='formfieldentity',
            name='entity_type',
            field=models.CharField(choices=[('text-input', 'Text Input'), ('text-area', 'Text Area'), ('multi-choice', 'Select Box'), ('check-boxes', 'Check Boxes')], max_length=12, verbose_name='Field Type'),
        ),
    ]
