# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20180223_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldentity',
            name='entity_choices',
            field=models.CharField(blank=True, max_length=100, verbose_name='Choices'),
        ),
    ]
