# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_formfieldentity_entity_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduledescriptionformversion',
            name='id',
        ),
        migrations.AddField(
            model_name='formfieldentity',
            name='module_description_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forms.ModuleDescriptionFormVersion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moduledescriptionformversion',
            name='module_description_version',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formfieldentity',
            name='entity_max_length',
            field=models.PositiveSmallIntegerField(default=500, verbose_name='Max Length'),
        ),
        migrations.AlterField(
            model_name='moduledescriptionformversion',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
