# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-03 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20180226_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldentity',
            name='entity_required',
            field=models.BooleanField(default=True),
        ),
    ]
