# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-03 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_formfieldentity_entity_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldentity',
            name='entity_label',
            field=models.CharField(max_length=100, verbose_name='Title/Label'),
        ),
    ]
