# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_auto_20180303_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledescription',
            name='form_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.ModuleDescriptionFormVersion'),
        ),
    ]
