# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20180222_1205'),
        ('forms', '0014_auto_20180305_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduledescription',
            old_name='module_code',
            new_name='module',
        ),
        migrations.AddField(
            model_name='moduledescription',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moduledescriptionentry',
            name='module_description_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forms.ModuleDescription'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='moduledescription',
            name='entries',
        ),
        migrations.AlterUniqueTogether(
            name='moduledescription',
            unique_together=set([('module', 'form_version')]),
        ),
    ]
