# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_auto_20180315_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledescriptionentry',
            name='integer_entry',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='moduledescriptionentry',
            name='string_entry',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
