# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_auto_20180317_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldentity',
            name='entity_type',
            field=models.CharField(choices=[('text-input', 'Text Input'), ('text-area', 'Text Area'), ('multi-choice', 'Select Box'), ('radio-buttons', 'Radio Buttons'), ('check-boxes', 'Check Boxes')], max_length=13, verbose_name='Field Type'),
        ),
    ]
