# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_auto_20180317_1621'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moduledescription',
            unique_together=set([]),
        ),
    ]
