# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20180222_1205'),
        ('forms', '0020_auto_20180322_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduleassessment',
            old_name='module_code',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='modulesoftware',
            old_name='module_code',
            new_name='module',
        ),
        migrations.RemoveField(
            model_name='modulesupport',
            name='module_code',
        ),
        migrations.RemoveField(
            model_name='moduleteaching',
            name='module_code',
        ),
        migrations.AddField(
            model_name='moduleassessment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulesoftware',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulesupport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulesupport',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moduleteaching',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moduleteaching',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Module'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modulesoftware',
            name='software_additional_comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='Additional Comments'),
        ),
        migrations.AlterField(
            model_name='modulesoftware',
            name='software_name',
            field=models.CharField(max_length=50, verbose_name='Software Name'),
        ),
        migrations.AlterField(
            model_name='modulesoftware',
            name='software_packages',
            field=models.CharField(blank=True, max_length=100, verbose_name='Packages'),
        ),
        migrations.AlterField(
            model_name='modulesoftware',
            name='software_version',
            field=models.CharField(blank=True, max_length=10, verbose_name='Version'),
        ),
    ]
