# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_auto_20180328_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleassessment',
            name='archive_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moduleassessment',
            name='current_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moduleassessment',
            name='staging_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulesoftware',
            name='archive_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulesoftware',
            name='current_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulesoftware',
            name='staging_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulesupport',
            name='archive_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulesupport',
            name='current_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulesupport',
            name='staging_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moduleteaching',
            name='archive_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moduleteaching',
            name='current_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moduleteaching',
            name='staging_flag',
            field=models.BooleanField(default=False),
        ),
    ]
