# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0022_auto_20180328_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleteaching',
            name='teaching_external_visits',
            field=models.PositiveSmallIntegerField(verbose_name='External Visits'),
        ),
        migrations.AlterField(
            model_name='moduleteaching',
            name='teaching_fieldworks',
            field=models.PositiveSmallIntegerField(verbose_name='Fieldwork'),
        ),
        migrations.AlterField(
            model_name='moduleteaching',
            name='teaching_lectures',
            field=models.PositiveSmallIntegerField(verbose_name='Classroom-based lectures'),
        ),
        migrations.AlterField(
            model_name='moduleteaching',
            name='teaching_online',
            field=models.PositiveSmallIntegerField(verbose_name='Scheduled online activities (Online versions on the above)'),
        ),
        migrations.AlterField(
            model_name='moduleteaching',
            name='teaching_placement',
            field=models.PositiveSmallIntegerField(verbose_name='Placement'),
        ),
        migrations.AlterField(
            model_name='moduleteaching',
            name='teaching_practical_workshops',
            field=models.PositiveSmallIntegerField(verbose_name='Practical classes and workshops'),
        ),
        migrations.AlterField(
            model_name='moduleteaching',
            name='teaching_schedule_assessment',
            field=models.PositiveSmallIntegerField(verbose_name='Scheduled examination/assessment'),
        ),
        migrations.AlterField(
            model_name='moduleteaching',
            name='teaching_supervised_time',
            field=models.PositiveSmallIntegerField(verbose_name='Supervised time in studio/laboratory/workshop'),
        ),
        migrations.AlterField(
            model_name='moduleteaching',
            name='teaching_tutorials',
            field=models.PositiveSmallIntegerField(verbose_name='Classroom-based seminars and/or tutorials'),
        ),
    ]
