# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_auto_20180328_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleassessment',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modulesoftware',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modulesupport',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='moduleteaching',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
