# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0024_auto_20180329_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleassessment',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='modulesoftware',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='modulesupport',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='moduleteaching',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='moduleassessment',
            name='seen_by_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulesoftware',
            name='seen_by_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulesupport',
            name='seen_by_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moduleteaching',
            name='seen_by_before',
            field=models.BooleanField(default=False),
        ),
    ]
