# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0025_auto_20180329_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleassessment',
            name='seen_by_before',
        ),
        migrations.RemoveField(
            model_name='modulesoftware',
            name='seen_by_before',
        ),
        migrations.RemoveField(
            model_name='modulesupport',
            name='seen_by_before',
        ),
        migrations.RemoveField(
            model_name='moduleteaching',
            name='seen_by_before',
        ),
    ]
