# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-30 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_module_seen_by_before'),
        ('forms', '0027_auto_20180330_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleReassessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reassessment_requested', models.BooleanField(default=False, verbose_name='Request change of reassessment method')),
                ('reassessment_new_method', models.CharField(blank=True, max_length=200, verbose_name='New reassessmenet method')),
                ('reassessment_rationale', models.TextField(blank=True, max_length=750)),
                ('archive_flag', models.BooleanField(default=False)),
                ('staging_flag', models.BooleanField(default=False)),
                ('current_flag', models.BooleanField(default=False)),
                ('version_number', models.IntegerField(default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='moduleexam',
            name='module_code',
        ),
        migrations.DeleteModel(
            name='ModuleExam',
        ),
    ]
