# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-30 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0028_auto_20180330_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulereassessment',
            name='reassessment_new_method',
            field=models.CharField(blank=True, max_length=200, verbose_name='New reassessment method'),
        ),
    ]
