# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-31 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0029_auto_20180330_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleassessment',
            name='copy_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='modulechangesummary',
            name='copy_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='modulereassessment',
            name='copy_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='modulesoftware',
            name='copy_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='modulesupport',
            name='copy_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='moduleteaching',
            name='copy_version',
            field=models.IntegerField(default=1),
        ),
    ]
