# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0031_auto_20180331_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldentity',
            name='entity_type',
            field=models.CharField(choices=[('text-input', 'Text Input'), ('text-area', 'Text Area'), ('multi-choice', 'Select Box'), ('radio-buttons', 'Radio Buttons'), ('check-box', 'Check Box')], max_length=13, verbose_name='Field Type'),
        ),
    ]
