# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-20 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0032_auto_20180404_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduledescription',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
