# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0034_auto_20180420_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduledescription',
            name='creation_date',
        ),
    ]
