# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0035_remove_moduledescription_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduledescription',
            name='archive_flag',
        ),
        migrations.RemoveField(
            model_name='moduledescription',
            name='current_flag',
        ),
        migrations.RemoveField(
            model_name='moduledescription',
            name='staging_flag',
        ),
    ]
