# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_yeartutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeartutor',
            name='tutor_year',
            field=models.CharField(choices=[('Year 1', 'Year 1'), ('Year 2', 'Year 2'), ('Year 3', 'Year 3'), ('MSC', 'MSC')], default='year 1', max_length=7, unique=True),
        ),
    ]
