# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 19:26
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180126_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=60)),
                ('module_credits', models.IntegerField(validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(10)])),
                ('module_level', models.CharField(max_length=10)),
                ('module_year', models.CharField(max_length=15)),
                ('semester', models.CharField(choices=[('Autumn Semester', 'autumn semester'), ('Sprint Semester', 'sprint semester'), ('Double Semester', 'double semester')], max_length=15)),
                ('delivery_language', models.CharField(choices=[('Welsh', 'welsh'), ('English', 'English')], max_length=10)),
                ('module_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['module_code'],
            },
        ),
        migrations.AlterModelOptions(
            name='yeartutor',
            options={'ordering': ['tutor_year']},
        ),
    ]
