# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180128_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='delivery_language',
            field=models.CharField(choices=[('Welsh', 'Welsh'), ('English', 'English')], max_length=10),
        ),
        migrations.AlterField(
            model_name='module',
            name='semester',
            field=models.CharField(choices=[('Autumn Semester', 'Autumn Semester'), ('Spring Semester', 'Spring Semester'), ('Double Semester', 'Double Semester')], max_length=15),
        ),
    ]
