# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_is_reviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(choices=[('CM1101', 'CM1101'), ('CM1102', 'CM1102'), ('CM1103', 'CM1103')], default='CM1101', max_length=6, unique=True)),
                ('reviewer_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['module_code'],
            },
        ),
    ]
