# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_reviewer',
            new_name='is_module_reviewer',
        ),
    ]
