# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180131_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewer',
            options={'ordering': ['module']},
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='module_code',
        ),
        migrations.AddField(
            model_name='reviewer',
            name='module',
            field=models.ForeignKey(default='not_set', on_delete=django.db.models.deletion.CASCADE, to='core.Module'),
            preserve_default=False,
        ),
    ]
