# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180202_1442'),
    ]

    operations = [
        migrations.RenameModel('YearTutor', 'ProgrammeTutor')
    ]
