# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180205_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.RenameField(
            model_name='programmetutor',
            old_name='year_tutor_user',
            new_name='programme_tutor_user',
        ),
        migrations.AddField(
            model_name='programmetutor',
            name='programme_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='programmetutor',
            name='tutor_year',
            field=models.CharField(choices=[('Year 1', 'Year 1'), ('Year 2', 'Year 2'), ('Year 3', 'Year 3'), ('MSC', 'MSC')], default='year 1', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='programmetutor',
            unique_together=set([('programme_name', 'tutor_year')]),
        ),
    ]
