# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180205_1912'),
        ('core', '0013_auto_20180202_1648'),
    ]

    operations = [
    ]
