# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20180207_1631'),
        ('core', '0014_merge_20180207_1713'),
    ]

    operations = [
    ]
