# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20180207_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='module_year',
        ),
        migrations.AddField(
            model_name='module',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
