# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20180208_1242'),
        ('core', '0015_auto_20180214_1837'),
    ]

    operations = [
    ]
