# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20180222_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_level',
            field=models.CharField(choices=[('L4', 'L4'), ('L5', 'L5'), ('L6', 'L6'), ('L7', 'L7')], max_length=2),
        ),
    ]
