# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180325_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmetutor',
            name='modules',
            field=models.ManyToManyField(to='core.Module'),
        ),
    ]
