# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_programmetutor_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
