# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_module_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='module',
            name='seen_by_before',
            field=models.BooleanField(default=False),
        ),
    ]
