# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180329_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='seen_by_before',
        ),
    ]
