# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineentry',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='timelineentry',
            name='created_by',
        ),
    ]
