# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_timelineentry_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineentry',
            name='entry_type',
            field=models.CharField(choices=[('Generic', 'Generic'), ('Init', 'Init'), ('Update', 'Update')], default='Generic', max_length=6),
        ),
    ]
