# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_auto_20180214_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablechange',
            old_name='changes_for',
            new_name='changes_for_model',
        ),
        migrations.RemoveField(
            model_name='tablechange',
            name='related_module',
        ),
        migrations.AddField(
            model_name='tablechange',
            name='model_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
