# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_auto_20180214_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablechange',
            name='model_app_label',
            field=models.CharField(default='core', max_length=30),
            preserve_default=False,
        ),
    ]
