# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('timeline', '0010_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineentry',
            name='module',
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='object_id',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
    ]
