# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0011_auto_20180222_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineentry',
            name='module_code',
            field=models.CharField(default='CM1234', max_length=10),
            preserve_default=False,
        ),
    ]
