# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0016_auto_20180317_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineentry',
            name='parent_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timeline.TimelineEntry'),
        ),
    ]
