# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0018_auto_20180329_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineentry',
            name='object_id',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
