# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-30 07:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline', '0021_auto_20180329_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineentry',
            name='changes_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changesby', to=settings.AUTH_USER_MODEL),
        ),
    ]
