# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-30 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0022_timelineentry_changes_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineentry',
            name='revert_object_id',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
