# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0023_timelineentry_revert_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineentry',
            name='entry_type',
            field=models.CharField(choices=[('Generic', 'Generic'), ('Tracking-Form', 'Tracking-Form'), ('Module-Description', 'Module-Description')], default='Generic', max_length=15),
        ),
    ]
