from .test_admin_new_user_view import *
from .test_admin_update_user_permissions_view import *
from .test_admin_year_tutor_list_view import *
from .test_admin_user_list_view import *
from .test_admin_year_tutor_create_view import *
from .test_admin_year_tutor_update_view import *
from .test_admin_module_list_view import *
from .test_admin_module_create_view import *
from .test_admin_module_update_view import *
