from django.contrib import admin


class ProgrammeTutorAdmin(admin.ModelAdmin):
    """
    Class to configure the YearTutor model
    for the admin panel generated by Django.
    """

    list_display = ('tutor_full_name', 'year_tutor_username', 'tutor_year')

    search_fields = ('tutor_full_name', 'year_tutor_username', 'tutor_year')
    ordering = ('tutor_year', )

    def tutor_full_name(self, obj):
        """
        Provide the full name of the user.
        """
        return obj.programme_tutor_user.get_full_name()

    def year_tutor_username(self, obj):
        """
        Provide the username of the user.
        """
        return obj.programme_tutor_user.username
