from django.contrib import admin


class ProgrammeTutorAdmin(admin.ModelAdmin):
    """
    Class to configure the ProgrammeTutor model
    for the admin panel generated by Django.
    """

    list_display = ('programme_name', 'tutor_year', 'tutor_name', 'tutor_username')

    search_fields = ('programme_name', 'tutor_year', 'tutor_name', 'tutor_username')
    ordering = ('tutor_year', )

    def tutor_name(self, obj):
        """
        Provide the full name of the user.
        """
        return obj.programme_tutor_user.get_full_name()

    def tutor_username(self, obj):
        """
        Provide the username of the user.
        """
        return obj.programme_tutor_user.username
